apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fsvu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-fsvu@sha256:94a1ca4c461b98973727349969e7b9e4e9003faf9cdd2a5b500b69417db325fb
        name: my-nodejs
        resources: {}
status: {}
